
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`
k_loaders_ready: 2
flatbed_trucks_ready: 4

